### ISSUE TITLE
How to run formatspread on an analysis task (text to JSON)

### ISSUE THREAD

**Issue by ResearchTLDR** [msclar/formatspread#1]
Since you mention that we can post an Issue for help with how to apply formatspread to a particular format, here goes!

I am working on the task of inputting a block of text along with a JSON format of information I want to extract from that text in order to get local LLMs to pull requested information from text. The closest publicly available dataset I have seen to this task is this one: https://huggingface.co/datasets/growth-cadet/news_to_json03

Since I have thousands of blocks of text that I want to analyze, it is worth spending some time to try several variations on the prompt formatting in order to find the most accurate format before continuing with the study. I have an RTX 3090 available for this project, and I'd be happy to run all 500 variations and share the results. I just need some help on how to get this format into something I can run with formatspread.

Just in case the dataset doesn't load, here is the first row, and it is split into three columns: instruction, context, response
**Instruction**
`You are a helpful assistant, who is required to analyse text from news article and return JSON with this schema: {{ "type": "financing", "company_name": <Name of the company raising funds>, "amount_raised_in_millions": <Amount of money raised in millions>, "funding_round": <Stage of the financing round. This can be one of the following: pre-seed, seed, series A/B/C/D/E/F/etc.'>, "investors": <An array of investor names ordered by contribution level to the round> "total_amount_raised_in_millions": <Total Amount of money that have been raised in milions> "currency":<currency of the money as short format>}} `

**Context**
`Title: Zillow Raises Another $25 million • TechCrunch Description: Seattle-based Zillow, which raised $32 million in funding in 2005 from Benchmark Capital and Technology Crossover Ventures, has raised another $25 million. This round of capital comes from a new investor, Boston-based Par Capital Mananement. No word on valuation. This comes on the heels of a recent (and massive) distribution deal with Yahoo. Zillow, essentially […] Content: . Zillow Raises Another $25 million./. 17 years. Seattle-based , which raised $32 million in funding in 2005 from Benchmark Capital and Technology Crossover Ventures, has raised another $25 million. This round of capital comes from a new investor, Boston-based Par Capital Mananement. No word on valuation..This comes on the heels of a recent (and massive).with Yahoo. Zillow, essentially a mashup of maps and historical real estate sales information, has now raised a whopping $57 million in capital. Other than supporting their 118 employees, it’s unclear what they plan to do with the money..has good information on Zillow’s recent stats, noting that in June the company had 2.1 million unique visitors, ranking 11th among real estate Web sites. Note that Jobster, another Seattle startup, has also.a large financing, bringing their total to nearly $50 million raised..Information provided by. `

**Response**
`{"type": "financing", "company_name": "Zillow", "amount_raised_in_millions": 25.0, "funding_round": "Not Specified", "investors": "Benchmark Capital, Technology Crossover Ventures, Par Capital Mananement", "total_amount_raised_in_millions": 57.0, "currency": "USD"}`

I suspect that the way the JSON Schema is described in the Instruction as well as the spacing and separators used between Instruction and Context could all impact the accuracy of a local LLM's response. In addition, I would like to try 1 and 3 shot prompting, so I need to test how the spacing and separators around the examples impact the Response.

I intend to test this on several local LLMs that all fit within 24GB of VRAM (at 8-bit quantization), like Mistral 7B, Llama 7B, Falcon 7B, Phi-2, etc.

Point me in the right direction, and I'd be happy to run some tests.

**Comment by msclar** [comment]
Hi!

If I understood correctly, the actual format of the input is a three-field setup, very similar to the [_two_text_fields()](https://github.com/msclar/formatspread/blob/main/grammar_definition.py#L618) but with one more format. 

Regarding changing the format of the output itself (e.g. the name of the JSON fields, the order, etc), FormatSpread does not currently support this, but we definitely welcome any PRs in this line! 

For context, in FormatSpread we kept the actual data of our study completely fixed, as our goal for the paper is not to prompt engineer but to encourage more thorough evaluation reports given the statistical validity issues we showed in the paper.

Best,
Melanie
